[versions]
java = "25"
kotlin = "2.0.20"
spring-boot = "4.0.2"
spring-dependency-management = "1.1.7"
lombok = "1.18.42"
springdoc = "3.0.1"
postgres = "42.7.3"
redis = "3.5+.5"
grpc = "1.65.1"
testcontainers = "1.21.3"
junit = "5.11.0"
mockito = "5.14.2"
jacoco = "0.8.12"

[libraries]
spring-boot-starter = { group = "org.springframework.boot", name = "spring-boot-starter", version.ref = "spring-boot" }
spring-boot-starter-web = { group = "org.springframework.boot", name = "spring-boot-starter-web", version.ref = "spring-boot" }
spring-boot-starter-data-jpa = { group = "org.springframework.boot", name = "spring-boot-starter-data-jpa", version.ref = "spring-boot" }
spring-boot-starter-data-redis = { group = "org.springframework.boot", name = "spring-boot-starter-data-redis", version.ref = "spring-boot" }
spring-boot-starter-actuator = { group = "org.springframework.boot", name = "spring-boot-starter-actuator", version.ref = "spring-boot" }
spring-boot-starter-validation = { group = "org.springframework.boot", name = "spring-boot-starter-validation", version.ref = "spring-boot"}
spring-boot-starter-logging = { group = "org.springframework.boot", name = "spring-boot-starter-logging", version.ref = "spring-boot" }
#spring-kafka = { group = "org.springframework.kafka", name = "spring-kafka", version.ref = "kafka" }
#spring-cloud-starter-kafka = { group = "org.springframework.cloud", name = "spring-cloud-starter-kafka", version.ref = "spring-cloud" }

postgresql = { group = "org.postgresql", name = "postgresql", version.ref = "postgres" }
redis-lettuce = { group = "io.lettuce", name = "lettuce-core", version.ref = "redis" }

lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
springdoc-openapi = { group = "org.springdoc", name = "springdoc-openapi-starter-webmvc-ui", version.ref = "springdoc" }

grpc-protobuf = { group = "io.grpc", name = "grpc-protobuf", version.ref = "grpc" }
grpc-stub = { group = "io.grpc", name = "grpc-stub", version.ref = "grpc" }

testcontainers-postgresql = { group = "org.testcontainers", name = "postgresql", version.ref = "testcontainers" }
testcontainers-junit-jupiter = { group = "org.testcontainers", name = "junit-jupiter", version.ref = "testcontainers" }

junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }
mockito-core = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
mockito-inline = { group = "org.mockito", name = "mockito-inline", version.ref = "mockito" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = {id = "io.spring.dependency-management", version.ref = "spring-dependency-management"}
jacoco = { id = "org.gradle.jacoco", version.ref = "jacoco" }
